# Generated by Django 3.2.6 on 2021-08-29 15:04

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20210103_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, validators=[django.contrib.auth.validators.UnicodeUsernameValidator], verbose_name='Username'),
        ),
    ]
