# Generated by Django 3.2.6 on 2021-08-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0011_auto_20210103_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitioncertificate',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='competition',
            name='slug',
            field=models.SlugField(blank=True, max_length=256, verbose_name='Slug'),
        ),
    ]
